spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
  jpa:
    show-sql: true
  redis:
    host: 192.168.200
    port: 6379
  rabbitmq:
    host: 192.168.26.200
    port: 5672
    username: guest
    password: guest
#通过配置实现ribbon的配置
PRODUCT: #通过配置来实现对ribbon，对产品的服务负载均衡
  ribbon:
    NFLoadBalancerRuleClassName:  com.netflix.loadbalancer.RandomRule #这里是要写class全名
env: 
  dev
